apiVersion: v1
baseDomain: $baseDomain
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    azure:
      type: $controlMachineSize
      osDisk:
        diskSizeGB: 1024
      zones: 
      - "1"
  replicas: $numControlReplicas
compute:
- hyperthreading: Enabled
  name: worker
  platform:
    azure:
      type: $workerMachineSize
      osDisk:
        diskSizeGB: 512 
  replicas: $numWorkerReplicas
metadata:
  name: $clusterName
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.40.0.0/16
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  azure:
    baseDomainResourceGroupName: $baseDomainResourceGroup
    virtualNetwork: $vnetName
    networkResourceGroupName: $resourceGroupName
    controlPlaneSubnet: $subnetControlNodeName
    computeSubnet: $subnetWorkerNodeName
    cloudName: AzurePublicCloud
    outboundType: Loadbalancer
    region: $deployRegion
publish: External
pullSecret: '$pullSecret'
sshKey: '$sshPubKey'
